In [1]:
# CV means Computer Vision

In [2]:
import cv2
img = cv2.imread ("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\kkk.jpg", 1)
print(img)

[[[216 225 212]
  [213 222 209]
  [210 219 206]
  ...
  [221 232 222]
  [224 235 225]
  [229 240 230]]

 [[216 225 212]
  [213 222 209]
  [211 220 207]
  ...
  [223 234 224]
  [225 236 226]
  [230 241 231]]

 [[216 225 212]
  [214 223 210]
  [213 222 209]
  ...
  [224 235 225]
  [226 237 227]
  [231 242 232]]

 ...

 [[176 184 197]
  [176 184 197]
  [176 184 197]
  ...
  [149 174 184]
  [149 175 182]
  [149 175 181]]

 [[176 184 197]
  [176 184 197]
  [176 184 197]
  ...
  [149 174 184]
  [149 175 182]
  [149 175 182]]

 [[175 183 196]
  [176 184 197]
  [176 184 197]
  ...
  [149 174 184]
  [149 175 182]
  [149 175 182]]]


In [3]:
import cv2
img = cv2.imread ("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\kkk.jpg", 0)
print(img)

[[220 217 214 ... 228 231 236]
 [220 217 215 ... 230 232 237]
 [220 218 217 ... 231 233 238]
 ...
 [187 187 187 ... 174 174 174]
 [187 187 187 ... 174 174 174]
 [186 187 187 ... 174 174 174]]


In [4]:
import cv2
img = cv2.imread ("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\kkk.jpg", 0)
print(type(img))

<class 'numpy.ndarray'>


In [5]:
import cv2
img = cv2.imread ("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\kkk.jpg", 1)
print(img.shape)

(1280, 590, 3)


In [6]:
import cv2
img = cv2.imread ("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\kkk.jpg", 1)
cv2.imshow("Legend", img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [7]:
import cv2
img = cv2.imread ("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\kkk.jpg", 1)
resized = cv2.resize(img, (600,600))
cv2.imshow("Legend", resized)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [8]:
import cv2
img = cv2.imread ("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\kkk.jpg", 1)
resized = cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("Legend", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import cv2
img = cv2.imread("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\kkk.jpg", 1)
resized = cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]*2)))
cv2.imshow("Legend", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
import cv2
face_cascade = cv2.CascadeClassifier("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\f.xml")
img = cv2.imread("C:\\Users\\KKK Fin Services\\anaconda3\\Projects\\Edureka\\f.jpg")
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray_img, scalefactor = 1.05, minNeighbors=5)
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w, x+h),(0,255,0),3)
    
resized = cv2.resize(img, (int(img.shape[1]),int(img.shape[0])))
cv2.imshow("Gray", resized)
cv2.waitkey(0)
cv2.destroyAllWindows()

error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'detectMultiScale'
> Overload resolution failed:
>  - 'scalefactor' is an invalid keyword argument for CascadeClassifier.detectMultiScale()
>  - 'scalefactor' is an invalid keyword argument for CascadeClassifier.detectMultiScale()


## Video Capturing 

In [ ]:
import cv2, time
video = cv2.VideoCapture(0)
check,frame = video.read()

print(check)
print(frame)
time.sleep(3)
video.release()